### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Timo2001** [AncestorComposition/public#1]
The provided API responds with internal server error does this mean the service of this project has been terminated entirely?

**Comment by Timo2001** [comment]
502 Bad Gateway error, so it might have messed up in the input json somewhere I guess?

**Comment by Timo2001** [comment]
Fixed it already, were some NaN values in JSON, had to preprocess the MH dataframe.

**Comment by AncestorComposition** [comment]
Hello Timo2001,
Glad that it is working for you!  What do you think of the results?
